import Title from '@/components/ui/title';
import Text from '@/components/ui/text';
import Tag from '@/components/ui/tag';
import Button from '@/components/ui/button';
import Avatar from '@/components/ui/avatar';

//* SVGs
import {
	LogoComplete,
	LogoMinified,
	MenuIcon,
	HomeIcon,
	HomeHeartIcon,
	HousesIcon,
	MaxPersonIcon,
	DollarCircleIcon,
	XCircleIcon,
	FamiliarPlaceIcon,
	LeafIcon,
	ParkIcon,
	MapPinIcon,
	StarIcon,
	RatingIcon,
	OutlinedRatingIcon,
	ACIcon,
	BedIcon,
	CarIcon,
	CctvIcon,
	ChalkboardIcon,
	ClosetIcon,
	ExtinguiserIcon,
	FanIcon,
	FridgeIcon,
	GrillIcon,
	HeatingIcon,
	OvenIcon,
	WifiIcon,
	ChevronIcon,
	FacebookIcon,
	InstagramIcon,
} from '@/components/ui/svgs';

export {
	Title,
	Text,
	Tag,
	Button,
	Avatar,
	LogoComplete,
	LogoMinified,
	MenuIcon,
	HomeIcon,
	HomeHeartIcon,
	HousesIcon,
	MaxPersonIcon,
	DollarCircleIcon,
	XCircleIcon,
	FamiliarPlaceIcon,
	LeafIcon,
	ParkIcon,
	MapPinIcon,
	StarIcon,
	RatingIcon,
	OutlinedRatingIcon,
	ACIcon,
	BedIcon,
	CarIcon,
	CctvIcon,
	ChalkboardIcon,
	ClosetIcon,
	ExtinguiserIcon,
	FanIcon,
	FridgeIcon,
	GrillIcon,
	HeatingIcon,
	OvenIcon,
	WifiIcon,
	ChevronIcon,
	FacebookIcon,
	InstagramIcon,
};
